//! Small, independently hand-verifiable normal-play CGT corpus.
//!
//! The expectations are definitions or standard examples from Conway, *On
//! Numbers and Games* (2nd ed., 2001); Berlekamp, Conway, and Guy, *Winning
//! Ways* (2nd ed., vol. 1, 2001); and Siegel, *Combinatorial Game Theory*
//! (2013). No expected result is generated by Thermograph itself.

use thermograph::{CGTValue, DyadicRational};

/// Absolute tolerance for the small integer/dyadic fixtures below.
const THERMOGRAPH_TOLERANCE: f32 = 1e-6;

fn assert_close(actual: f32, expected: f32, label: &str) {
    assert!(
        (actual - expected).abs() <= THERMOGRAPH_TOLERANCE,
        "{label}: expected {expected}, got {actual}"
    );
}

fn switch(left: i32, right: i32) -> CGTValue {
    CGTValue::GameTree {
        left: vec![CGTValue::Integer(left)],
        right: vec![CGTValue::Integer(right)],
    }
}

#[test]
fn exact_number_fixture_uses_normalized_dyadics() {
    // 2/4 = 1/2 and 1/2 + 3/4 = 5/4.
    let half = DyadicRational::new(2, 2);
    let three_quarters = DyadicRational::new(3, 2);

    assert_eq!(half, DyadicRational::new(1, 1));
    assert_eq!(half.add(&three_quarters), DyadicRational::new(5, 2));
    assert_eq!(
        half.add(&three_quarters).to_cgt_value(),
        CGTValue::Dyadic(5, 2)
    );

    let number = CGTValue::Dyadic(1, 1).approximate_thermograph();
    assert_close(number.temperature, -1.0, "number temperature convention");
    assert_close(number.mean, 0.5, "number mean");
}

#[test]
fn switch_mean_and_temperature_follow_cooling_intersection() {
    // For a numeric switch {a | b}, a > b, the two initial walls intersect at
    // mean (a+b)/2 and temperature (a-b)/2.
    let symmetric = switch(1, -1).approximate_thermograph();
    assert_close(symmetric.mean, 0.0, "{1|-1} mean");
    assert_close(symmetric.temperature, 1.0, "{1|-1} temperature");

    let shifted = switch(3, 1).approximate_thermograph();
    assert_close(shifted.mean, 2.0, "{3|1} mean");
    assert_close(shifted.temperature, 1.0, "{3|1} temperature");
}

#[test]
fn named_infinitesimal_fixtures_remain_distinct_from_zero() {
    for (label, game) in [
        ("star", CGTValue::Star),
        ("up", CGTValue::Up),
        ("down", CGTValue::Down),
    ] {
        let approximation = game.approximate_thermograph();
        assert_close(approximation.mean, 0.0, &format!("{label} mean"));
        assert_close(
            approximation.temperature,
            0.0,
            &format!("{label} temperature"),
        );
        assert_ne!(game, CGTValue::Integer(0));
        assert!(game.try_to_dyadic().is_none());
    }
}

#[test]
fn exact_sums_and_negation_match_hand_algebra() {
    assert_eq!(
        CGTValue::sum_all([
            CGTValue::Integer(1),
            CGTValue::Dyadic(1, 1),
            CGTValue::Dyadic(-1, 2),
        ]),
        CGTValue::Dyadic(5, 2),
    );

    let game = switch(3, 1);
    assert_eq!(game.negate(), switch(-1, -3));
    let negated = game.negate().approximate_thermograph();
    assert_close(negated.mean, -2.0, "negated switch mean");
    assert_close(negated.temperature, 1.0, "negated switch temperature");
}

#[test]
fn domination_removes_only_the_weaker_numeric_options() {
    // In {1, 0 | -1, 0}, Left never benefits from choosing 0 over 1 and Right
    // never benefits from choosing 0 over -1.
    let unsimplified = CGTValue::GameTree {
        left: vec![CGTValue::Integer(1), CGTValue::Integer(0)],
        right: vec![CGTValue::Integer(-1), CGTValue::Integer(0)],
    };
    let simplified = unsimplified.simplify();

    assert_eq!(simplified, switch(1, -1));
    assert_ne!(
        unsimplified.canonical_serialization(),
        simplified.canonical_serialization(),
        "structural identity intentionally differs before simplification"
    );
}

#[test]
fn reversible_star_option_bypasses_to_empty_tree() {
    // In {* | }, Right's reply from * reaches 0 <= G, so the reversible Left
    // option is bypassed. The structural result is the empty zero tree.
    let left_reversible = CGTValue::GameTree {
        left: vec![CGTValue::Star],
        right: vec![],
    };
    let right_reversible = CGTValue::GameTree {
        left: vec![],
        right: vec![CGTValue::Star],
    };
    let empty = CGTValue::GameTree {
        left: vec![],
        right: vec![],
    };

    assert_eq!(left_reversible.simplify(), empty);
    assert_eq!(right_reversible.simplify(), empty);
}

#[test]
#[allow(deprecated)]
fn deprecated_exact_name_is_a_compatible_approximation_wrapper() {
    let game = switch(1, -1);
    let new_api = game.approximate_thermograph();
    let old_api = game.exact_thermograph();

    assert_eq!(old_api.0, new_api.temperature);
    assert_eq!(old_api.1, new_api.mean);
    assert_eq!(old_api.2, new_api.left_scaffold);
    assert_eq!(old_api.3, new_api.right_scaffold);
}
